# Generated by Django 4.0.5 on 2022-06-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floatingbutton',
            name='type',
            field=models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], default='NO', max_length=30, null=True, verbose_name='Тип обращения(обратный звонок)'),
        ),
    ]
