# Generated by Django 4.0.5 on 2022-06-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_floatingbutton_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floatingbutton',
            name='available',
        ),
    ]
