# Generated by Django 4.0.5 on 2022-06-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_help_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={},
        ),
        migrations.AlterField(
            model_name='help_image',
            name='image_help',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
