# Generated by Django 4.0.5 on 2022-06-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_help_options_alter_help_image_image_help'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name_plural': 'Помощь'},
        ),
        migrations.AlterField(
            model_name='help_image',
            name='image_help',
            field=models.ImageField(blank=True, upload_to='products', verbose_name='Картинки'),
        ),
    ]
