# Generated by Django 4.0.5 on 2022-06-14 05:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_help_options_alter_help_image_image_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='products', verbose_name='Картинка')),
                ('image2', models.ImageField(upload_to='products', verbose_name='Картинка')),
                ('image3', models.ImageField(upload_to='products', verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.DeleteModel(
            name='About_us',
        ),
        migrations.AlterModelOptions(
            name='help_image',
            options={'verbose_name_plural': 'Картинка для помощи'},
        ),
    ]
