# Generated by Django 4.0.5 on 2022-06-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_aboutus_delete_about_us_alter_help_image_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image2',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image3',
            field=models.ImageField(upload_to='products'),
        ),
    ]
