# Generated by Django 4.0.5 on 2022-06-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_aboutus_image2_alter_aboutus_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='image2',
            field=models.ImageField(upload_to='products', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image3',
            field=models.ImageField(upload_to='products', verbose_name='Картинка'),
        ),
    ]
