# Generated by Django 4.0.5 on 2022-06-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_aboutus_image2_alter_aboutus_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='Ввод данных')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Инстаграм')),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ватсапп')),
                ('telegram', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телеграм')),
                ('mail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта')),
                ('num', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': 'Футер и хедер'},
        ),
        migrations.RemoveField(
            model_name='footer',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='num',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='number',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='whatsapp',
        ),
    ]
