# Generated by Django 4.0.5 on 2022-06-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество в линейке')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productitemimage', verbose_name='Картинка товара')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='order.order', verbose_name='Заказы')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
