# Generated by Django 4.0.5 on 2022-06-15 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество в линейке')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productitemimage', verbose_name='Картинка товара')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Корзинa',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('mail', models.CharField(blank=True, max_length=50, null=True, verbose_name='Почта')),
                ('num', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('date_order', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата оформления')),
                ('status', models.CharField(choices=[('Оформлен', 'Оформлен'), ('Отменен', 'Отменен'), ('Новый', 'Новый')], db_index=True, default=('Новый', 'Новый'), max_length=255, verbose_name='Выбор из списка')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Общая цена до учета скидок')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sum', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество линеек')),
                ('sum_quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество всех товаров в линейках')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма всех скидок')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Итого к оплате')),
                ('cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='related_cart', to='basket.cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='basket.order')),
            ],
        ),
    ]
