# Generated by Django 4.0.5 on 2022-06-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('mail', models.CharField(max_length=50, null=True, verbose_name='Почта')),
                ('num', models.CharField(max_length=30, null=True, verbose_name='Номер')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='Страна')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='Город')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления')),
                ('status', models.CharField(choices=[('Оформлен', 'Оформлен'), ('Отменен', 'Отменен'), ('Новый', 'Новый')], db_index=True, default=('Новый', 'Новый'), max_length=255, verbose_name='Статус заказа')),
                ('number_of_lines', models.IntegerField(default=0, verbose_name='Количество линеек')),
                ('number_of_goods', models.IntegerField(default=0, verbose_name='Количество всех товаров в линейках')),
                ('total_price_before_discount', models.IntegerField(default=0, verbose_name='Общая цена до учета скидок')),
                ('total_discounted_price', models.IntegerField(default=0, verbose_name='Сумма всех скидок')),
                ('discount_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма скидки')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productitemimage', verbose_name='Фото')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='basket.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Заказанные товары',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_products', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество товаров')),
                ('price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество в линейке')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productitemimage', verbose_name='Картинка товара')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Корзинa',
            },
        ),
    ]
