# Generated by Django 4.0.5 on 2022-06-20 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_order_discount_amount_order_number_of_goods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number_of_goods',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number_of_lines',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_discounted_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price_before_discount',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_lines', models.IntegerField(default=0, verbose_name='Количество линеек')),
                ('number_of_goods', models.IntegerField(default=0, verbose_name='Количество всех товаров в линейках')),
                ('total_price_before_discount', models.IntegerField(default=0, verbose_name='Общая цена до учета скидок')),
                ('total_discounted_price', models.IntegerField(default=0, verbose_name='Сумма всех скидок')),
                ('discount_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Сумма скидки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_order', to='basket.order')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
