# Generated by Django 4.0.5 on 2022-06-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_remove_orderitem_user_alter_orderitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Общее количество заказов'},
        ),
    ]
