# Generated by Django 4.0.5 on 2022-06-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_order_discount_amount_order_number_of_goods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_discounted_price',
            field=models.IntegerField(default=0, verbose_name='Сумма после скидки'),
        ),
    ]
