# Generated by Django 4.0.5 on 2022-06-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mail',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Почта'),
            preserve_default=False,
        ),
    ]
