# Generated by Django 4.0.5 on 2022-06-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_alter_order_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, default=1, max_length=30, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='lastname',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
