# Generated by Django 4.0.5 on 2022-06-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0006_alter_order_total_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number_of_goods',
            field=models.IntegerField(default=0, verbose_name='Количество линеек'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_lines',
            field=models.IntegerField(default=0, verbose_name='Количество всех товаров в линейках'),
        ),
    ]
