# Generated by Django 4.0.5 on 2022-06-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_alter_order_city_alter_order_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart',
        ),
    ]
